// ignore_for_file: constant_identifier_names

const home_tittle = 'Upcoming Events';
const book_ticket = 'Book ticket';
const view_seats = 'view seats';
const home = 'Home';
const bookmark = 'Bookmarks';
const profile = 'Profile';
const no_shows = 'No shows available';
const dismiss = 'Dismiss';
const purchase = 'Purchase';
const phone_number = 'Phone Number';
const number_tickets = 'Number of tickets';
const name = 'name';
const email = 'Email';
const payment_details = 'Payment Details';
const description = 'Description';
const event_owner = 'event organised by';
const logout = 'Logout';
const schedule_text = 'Scheduled for';
const confirm_logout ="Confirm Logout";
const logout_text = "Are you sure you want to logout?";
const cancel ="Cancel";
const wrong_email ='correct email needed to ticket details';
const ticket_name ='name to appear on ticket';
const number_billing='number required for billing';
const valid_number ='Please enter a valid phone number';
const ticket_number='Please enter the number of tickets';
const search_text='Search events by name';